# build and push image to hub.docker.com

trigger:
- master

resources:
- repo: self

variables:
  tag: 'latest' # tag, target: mylogin/image-name:latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerHub)'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: '$(dockerHub)'
        repository: '$(imageName)'
        command: 'push'
        tags: |
          $(tag)