# build and push image to hub.docker.com

trigger:
- master

resources:
- repo: 'https://github.com/mguazzardo/apiflask'

variables:
  dockerHub: 'dockerHub' # specify your service connection name (create in previos step)
  imageName: 'mguazzardo/pruf' # your desired image name, format: mylogin/image-name
  tag: 'latest' # tag, target: mylogin/image-name:latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerHub)'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: '$(dockerHub)'
        repository: '$(imageName)'
        command: 'push'
        tags: |
          $(tag)